### ISSUE TITLE
Alteração na sessão wiki

### ISSUE THREAD

**Issue by lucasdeshok** [UnbDroid/AprendendoGithub#1]
Na seção wiki para o tutorial em português, o título está descrito da seguinte forma 'r## Curso Git'.
Penso que tenha sido um erro de digitação, sendo necessário substituir a letra 'r' por cerquilha '#', para que fique no mesmo padrão do tutorial escrito em inglês.

**Comment by zaitera** [comment]
Obrigado pelo aviso @lucasdeshok, já corrigimos
